-- CREATE DATABASE ping_pong;

DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS matches;

CREATE TABLE players (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50),
  points INTEGER NOT NULL
);

CREATE TABLE matches (
  id SERIAL PRIMARY KEY,
	p1 INTEGER NOT NULL,
	p2 INTEGER NOT NULL,
	winner INTEGER NOT NULL,
	score VARCHAR(50) NOT NULL,
	p1_diff INTEGER NOT NULL,
	p2_diff INTEGER NOT NULL,
	date_played VARCHAR(50) NULL
);
